name: CI
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          cache: yarn
          node-version-file: '.nvmrc'

      - name: "Yarn: Install dependencies"
        run: yarn install --frozen-lockfile --non-interactive
      
      - name: Build package
        run: yarn build
      
      - name: Lint package
        run: yarn lint
      
      - name: Test package
        run: yarn test
